import { Service } from '../../models';
import { STATIC_SERVICE_IMAGES } from './static-images';

/** Full static service catalog — no backend required */
export const STATIC_SERVICES: Service[] = [
  {
    id: 'gel-nails',
    name: 'Gel Nails',
    slug: 'gel-nails',
    description: 'High-shine gel colour with a lasting top coat — luminous polish that stays mirror-smooth for weeks.',
    price: 1200,
    duration_minutes: 75,
    image_url: STATIC_SERVICE_IMAGES['gel-nails'],
    category: 'gel',
    is_featured: true,
    is_active: true,
    sort_order: 0,
  },
  {
    id: 'acrylic-nails',
    name: 'Acrylic Nails',
    slug: 'acrylic-nails',
    description: 'Sculpted acrylic strength with refined shape — built for everyday elegance and lasting structure.',
    price: 1800,
    duration_minutes: 120,
    image_url: STATIC_SERVICE_IMAGES['acrylic-nails'],
    category: 'acrylic',
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'french-nails',
    name: 'French Nails',
    slug: 'french-nails',
    description: 'The classic reinterpreted — soft nude base, crisp white tips, and timeless almond restraint.',
    price: 1500,
    duration_minutes: 90,
    image_url: STATIC_SERVICE_IMAGES['french-nails'],
    category: 'french',
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'bridal-nails',
    name: 'Bridal Nails',
    slug: 'bridal-nails',
    description: 'Milky bridal sets with lace detail and pearl accents — composed for your wedding week.',
    price: 2500,
    duration_minutes: 150,
    image_url: STATIC_SERVICE_IMAGES['bridal-nails'],
    category: 'bridal',
    is_featured: true,
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'chrome-nails',
    name: 'Chrome Nails',
    slug: 'chrome-nails',
    description: 'Liquid-metal mirror chrome — reflective finishes with soft depth and modern shine.',
    price: 2000,
    duration_minutes: 100,
    image_url: STATIC_SERVICE_IMAGES['chrome-nails'],
    category: 'chrome',
    is_featured: true,
    is_active: true,
    sort_order: 4,
  },
  {
    id: '3d-nail-art',
    name: '3D Nail Art',
    slug: '3d-nail-art',
    description: 'Raised florals, droplet texture, and champagne-gold centres — wearable sculpture nail by nail.',
    price: 2800,
    duration_minutes: 160,
    image_url: STATIC_SERVICE_IMAGES['3d-nail-art'],
    category: 'luxury',
    is_featured: true,
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'nail-extensions',
    name: 'Nail Extensions',
    slug: 'nail-extensions',
    description: 'Almond-length extensions in milky nude with a quiet gold stud — light, precise, and couture.',
    price: 2200,
    duration_minutes: 135,
    image_url: STATIC_SERVICE_IMAGES['nail-extensions'],
    category: 'extensions',
    is_featured: true,
    is_active: true,
    sort_order: 6,
  },
  {
    id: 'cat-eye-nails',
    name: 'Cat Eye Nails',
    slug: 'cat-eye-nails',
    description: 'Magnetic forest-green shimmer with a luminous cat-eye band — depth that shifts with every turn of the hand.',
    price: 1900,
    duration_minutes: 95,
    image_url: STATIC_SERVICE_IMAGES['cat-eye-nails'],
    category: 'chrome',
    is_featured: true,
    is_active: true,
    sort_order: 7,
  },
  {
    id: 'minimal-nail-art',
    name: 'Minimal Nail Art',
    slug: 'minimal-nail-art',
    description: 'Quiet black linework on milky nude — minimal artistry with maximum polish.',
    price: 1600,
    duration_minutes: 90,
    image_url: STATIC_SERVICE_IMAGES['minimal-nail-art'],
    category: 'minimal',
    is_featured: false,
    is_active: true,
    sort_order: 8,
  },
  {
    id: 'luxury-nail-art',
    name: 'Luxury Nail Art',
    slug: 'luxury-nail-art',
    description: 'Couture burgundy sets with gold foil, pearls, and sculpted charms — bespoke luxury composed nail by nail.',
    price: 3000,
    duration_minutes: 180,
    image_url: STATIC_SERVICE_IMAGES['luxury-nail-art'],
    category: 'luxury',
    is_featured: true,
    is_active: true,
    sort_order: 9,
  },
];

export function getFeaturedServices(): Service[] {
  return STATIC_SERVICES.filter((s) => s.is_featured).sort((a, b) => a.sort_order - b.sort_order);
}

export function getServiceBySlug(slug: string): Service | undefined {
  return STATIC_SERVICES.find((s) => s.slug === slug);
}
